name: CI

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        java_version: ["19"]
        maven_version: ["3.6.2"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven=${{ matrix.maven_version }}

      - name: Verify Java and Maven versions
        run: |
          java -version
          mvn -version

      # Continue with your build steps here
