name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 18
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 18.0.1.fx-zulu

      - name: Download and install Maven 3.6.2
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          
          # Download and extract Maven 3.6.3
          wget https://apache.osuosl.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar xf apache-maven-3.9.6-bin.tar.gz
          sudo mv apache-maven-3.9.6 /opt/maven
          sudo ln -s /opt/maven/bin/mvn /usr/local/bin/mvn


      - name: Verify Java and Maven versions
        run: |
          java -version
          mvn -version

      - name: Compile code
        run: mvn compile

      - name: Run tests
        run: mvn test
