name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 19
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 19.3.0.fx-zulu
          echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
          echo "sdkman_auto_selfupdate=true" >> ~/.sdkman/etc/config
          sdk selfupdate force
          sdk use java 19.3.0.fx-zulu

      - name: Download and install Maven 3.6.2
        run: |
            wget https://apache.osuosl.org/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
            tar xf apache-maven-3.6.2-bin.tar.gz
            sudo mv apache-maven-3.6.2 /opt/maven
            sudo update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 1001


      - name: Verify Java and Maven versions
        run: |
          java -version
          mvn -version

      - name: Compile code
        run: mvn compile

      - name: Run tests
        run: mvn test
